### ISSUE TITLE
Nouvelle arme : grenade fumigène

### ISSUE THREAD

**Issue by Aur36** [PifyZ/project-fighting#15]
Une grenade lançable qui serait fumigène
Caractéristiques : 
- Rayon plus grand que celui d'une grenade à fragmentation
- Assombrit l'écran des joueurs présents à l'intérieur (ils ne peuvent voir clairement que dans un rayon limité autour d'eux, rayon qui se déplace)
- Les joueurs à l'extérieur ne voient que de la fumée

**Comment by PifyZ** [comment]
Arme ajoutée.

Comportement : libère de la fumée.
