### ISSUE TITLE
Utiliser l'anglais et non le Français

### ISSUE THREAD

**Issue by flofly** [PifyZ/project-fighting#8]
Hello,

Vous devriez rédiger la doc et les commentaires en anglais afin de toucher une audience plus large.

**Comment by PifyZ** [comment]
Bonjour,

bien que j'arrive plus ou moins à lire l'anglais, je suis assez médiocre quand il s'agit de l'écrire ou de le parler.

Les commentaires sont là pour m'aider dans la compréhension du code. Si je les écris moi-même en anglais, cela risque d'être dans un mauvais anglais et de me perturber dans une relecture future ou de perturber de potentiels contributeurs.

De plus, il s'agit d'un petit projet dont je doute fort qu'il y ait un grand nombre de contributeurs. Cependant, si jamais il s'avère qu'il y ait beaucoup de contributeurs qui parlent anglais, j'agirais en conséquence.

Bien sûr, le fait que les commentaires et la documentation soit en français peut rebuter les anglophones à participer au projet, mais je suis prêt à prendre le risque pour l'instant.

Je vous remecie pour l'intérêt que vous portez au projet. J'espère que vous comprenez mon point de vue.

**Comment by flofly** [comment]
Oui je comprends très bien, c'est plus un conseil qu'un issue ;)

Moi qui suis Français je m'efforce de tout écrire en anglais pour éviter ce travail supplémentaire le jour ou il y en a besoin.

Mais je comprends votre point de vue.
